name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://wyt52566-my.sharepoint.com/personal/mandfx_lones_me/_layouts/15/download.aspx?UniqueId=5b55963d-3b25-475a-95bb-37577997f9f0&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvd3l0NTI1NjYtbXkuc2hhcmVwb2ludC5jb21ANTRjNDdmZGMtMzJlOC00MDJlLWFiNGUtNjg5MmM4NWIxNjM3IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU5NDM3Mjc0NSIsImV4cCI6IjE1OTQzNzYzNDUiLCJlbmRwb2ludHVybCI6Ikt4cUNZcmd1ajREUmwvem9sdklJbDBUTnF0OGlZMHdtWnovUUxORnUvT2M9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNDciLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6IllUWmhZMk5tWWpZdE9EZGlZUzAwT1dFMkxXSTFaR1F0T0dKaU16RmhZalF4T0RZMSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJOVFZpWVdNMVltSXRZekJoTUMwME5EUmhMVGhsTmpNdFlUWXpOVFExTWpaaE1UazEiLCJhcHBfZGlzcGxheW5hbWUiOiJvbmVpbmRleCIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6IjNkMzhkMzk5LTRiM2QtNGRkZS1hMDhiLTk3YWFhZTYzMDc3NSIsInRpZCI6IjU0YzQ3ZmRjLTMyZTgtNDAyZS1hYjRlLTY4OTJjODViMTYzNyIsInVwbiI6Im1hbmRmeEBsb25lcy5tZSIsInB1aWQiOiIxMDAzMjAwMENEMDZFMTAxIiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDBjZDA2ZTEwMUBsaXZlLmNvbSIsInNjcCI6ImFsbGZpbGVzLndyaXRlIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.VGphRDMzL255WWZieFYxTWxUYlNDZDNTakNiaW13alQzWmJJMFh1QUozUT0&ApiVersion=2.0
  ROM_NAME: MIUI:MANDFX
  ZIP_NAME: Mandfx
  TZ: Asia/Kolkata
  MIR: wet
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/JamieHoSzeYui/ErfanGSIs -b curtana
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
